**Ejercicio 1**

- Crear una lista de número secuenciales con el valor mínimo de 10 y el valor máximo 39
- Convierte esta lista en una lista o matriz de 2 dimensiones (3 filas por 10 columnas)
- Muestra por pantalla el valor del elemento de la esquina superior derecha de la matriz

In [23]:
import numpy as np

In [67]:
lista = np.arange(10,40)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [87]:
lista = lista.reshape(3,10)
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [118]:
# función para encontrar las coordenadas de los elementos que cumplen con cierta condición
# si no lo encuentra, retorna None
posicion = np.argwhere(lista == 19)
print("coordenadas: ", posicion)
print(lista[0][9])

coordenadas:  [[0 9]]
19


---
**Ejercicio 2**
- Crear un array de una dimensión con 9 valores enteros aleatorios entre 0 y 100
- Convierte ese array en una matriz de 2 dimensiones (3 filas y 3 columnas)
- Muestra por pantalla el valor del elemento de la matriz de la esquina inferior derecha

In [100]:
array = np.random.randint(0,100,9)
array

array([45, 37,  1, 13, 29, 78, 39, 70, 32])

In [114]:
matriz = array.reshape(3,3)
matriz

array([[45, 37,  1],
       [13, 29, 78],
       [39, 70, 32]])

In [116]:
matriz[2,2]

32