**Numpy arrays**

In [12]:
import numpy as np

In [26]:
lista = [1,2,3,4]
array = np.array(lista)
array

array([1, 2, 3, 4])

In [28]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(lista2)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
**Numpy arrays - arange, zeros, ones, linspace, eye**

In [78]:
# np.arange(start, stop, step): crea un arreglo de valores equidistantes.
print(np.arange(5))
print(np.arange(2,10))
print(np.arange(2,10,2))

[0 1 2 3 4]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [93]:
print("Vector unidimensional:\n", np.zeros(3)) # np.zeros(size): crea un vector con size ceros.
print("Vector bidimensional:\n", np.zeros((3,4))) # np.zeros((rows, cols)): crea una matriz de ceros.

Vector unidimensional:
 [0. 0. 0.]
Vector bidimensional:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [95]:
print("Vector unidimensional\n", np.ones(3)) # np.ones(size): crea un vector con size unos.
print("Vector bidimensional:\n", np.ones((2,5))) # np.ones((rows, cols)): crea una matriz de unos.

Vector unidimensional
 [1. 1. 1.]
Vector bidimensional:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [97]:
# np.linspace(start, stop, num): crea un arreglo desde start hasta stop, con num elementos
np.linspace(3,9,20)

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [119]:
# np.eye(N): crea una matriz identidad de tamaño N x N (1 en la diagonal principal, 0 en el resto).
print(np.eye(5), "\n")
print(np.eye(5, k=2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---
**Numpy arrays - números aleatorios - rand y randn**

In [107]:
print("Vector unidimensional:\n", np.random.rand(5)) # np.random.rand(N): crea un array de N valores aleatorios con una distribución uniforme entre 0 y 1
print("Vector bidimensional:\n", np.random.rand(2,3)) # np.random.rand((N,M)): crea una array de N filas y M columnas con valores aleatorios entre 0 y 1

Vector unidimensional:
 [0.95584238 0.71817869 0.33157727 0.03112579 0.6797161 ]
Vector bidimensional:
 [[0.13506774 0.39355379 0.81937304]
 [0.46148278 0.95396872 0.09706255]]


In [111]:
print("Vector unidimensional:\n", np.random.randn(4)) # np.random.randn(N): crea un array de N valores aleatorios con media 0 y desviación estándar 1
print("Vector bidimensional:\n", np.random.randn(4,5)) # np.random.randn(N,M): crea un array de N filas y M columnas con media 0 y desviación estándar 1

Vector unidimensional:
 [-0.16040288  0.25536177  0.79462037  0.146758  ]
Vector bidimensional:
 [[ 0.4005459  -0.96265361 -0.12026863  1.78022216  0.01391601]
 [ 1.00626049 -1.25625863 -0.37470226  0.50147927  0.12071055]
 [ 0.93341621 -0.27851559  0.31271257  1.48592041 -0.52051647]
 [ 1.19019978 -0.58716333  2.02486668  0.08246705  0.46032955]]
