## Sección 4: Módulo Numpy para análisis de datos

In [1]:
import numpy as np

---
### Numpy arrays

In [3]:
lista = [1,2,3,4]
array = np.array(lista)
array

array([1, 2, 3, 4])

In [4]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(lista2)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
### Numpy arrays - arange, zeros, ones, linspace, eye

In [6]:
# np.arange(start, stop, step): crea un arreglo de valores equidistantes.
print(np.arange(5))
print(np.arange(2,10))
print(np.arange(2,10,2))

[0 1 2 3 4]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [7]:
print("Vector unidimensional:\n", np.zeros(3)) # np.zeros(size): crea un vector con size ceros.
print("Vector bidimensional:\n", np.zeros((3,4))) # np.zeros((rows, cols)): crea una matriz de ceros.

Vector unidimensional:
 [0. 0. 0.]
Vector bidimensional:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
print("Vector unidimensional\n", np.ones(3)) # np.ones(size): crea un vector con size unos.
print("Vector bidimensional:\n", np.ones((2,5))) # np.ones((rows, cols)): crea una matriz de unos.

Vector unidimensional
 [1. 1. 1.]
Vector bidimensional:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# np.linspace(start, stop, num): crea un arreglo desde start hasta stop, con num elementos
np.linspace(3,9,20)

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [10]:
# np.eye(N): crea una matriz identidad de tamaño N x N (1 en la diagonal principal, 0 en el resto).
print(np.eye(5), "\n")
print(np.eye(5, k=2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---
### Numpy arrays - números aleatorios - rand y randn

In [12]:
# np.random.rand(N): crea un array de N valores aleatorios con una distribución uniforme entre 0 y 1
print("Vector unidimensional:\n", np.random.rand(5))

# np.random.rand((N,M)): crea una array de N filas y M columnas con valores aleatorios entre 0 y 1
print("Vector bidimensional:\n", np.random.rand(2,3))

Vector unidimensional:
 [0.14029871 0.28766428 0.79718663 0.8468237  0.33664795]
Vector bidimensional:
 [[0.79936409 0.97457139 0.93867758]
 [0.09724918 0.39800469 0.24988747]]


In [13]:
# np.random.randn(N): crea un array de N valores aleatorios con media 0 y desviación estándar 1
print("Vector unidimensional:\n", np.random.randn(4))

# np.random.randn(N,M): crea un array de N filas y M columnas con media 0 y desviación estándar 1
print("Vector bidimensional:\n", np.random.randn(4,5))

Vector unidimensional:
 [0.73315533 1.49415717 0.66843163 0.16896146]
Vector bidimensional:
 [[-1.09496242  0.02493225 -0.43961353 -0.17304301  0.83554222]
 [-0.69343587 -1.13428378 -0.7664597   0.79572387 -0.34267459]
 [ 1.4005368   2.70217207 -0.65596375 -1.22993446 -0.12602424]
 [ 0.73086939 -1.75060993 -0.63922624 -0.76685321 -0.02736885]]


---
### Numpy arrays - números aleatorios enteros, randint

In [15]:
print(np.random.randint(1,20)) # genera un número aleatorio entre 1 y 20
print("\n", np.random.randint(1,20,5)) # generar 5 números aleatorios entre 1 y 20
print("\n", np.random.randint(1,20,(5,5))) # 5 x 5 matriz de números aleatorios entre 1 y 20

10

 [12 13 12  2  9]

 [[13 19 15 11 15]
 [12  3 15  5 12]
 [ 1 15 13 14 16]
 [14  1  6  4 13]
 [ 2 15  1 12 14]]


---
### Numpy arrays - reshape

In [17]:
array = np.random.randint(1,100,25)
array

array([82, 28, 94, 30, 31,  1, 95, 11, 37, 39, 65, 97, 49, 18, 13, 52, 71,
        1,  1, 46, 85, 57, 51, 14,  3])

In [18]:
matriz = array.reshape(5,5) # el número de row x número de col debe ser igual a 25
matriz

array([[82, 28, 94, 30, 31],
       [ 1, 95, 11, 37, 39],
       [65, 97, 49, 18, 13],
       [52, 71,  1,  1, 46],
       [85, 57, 51, 14,  3]])

---
### Numpy arrays - max y min

In [20]:
array = np.random.randint(1,100,50)
array

array([71, 80, 23, 99, 68, 92, 87, 86, 27, 94, 62, 36, 12,  6, 81, 68, 23,
       81, 94, 77, 40, 63, 80, 55, 51, 55, 79, 57, 99,  9,  8, 80, 41, 76,
       98, 97,  4,  1, 23, 57, 21, 99, 38, 94, 90, 49, 86, 58, 45, 65])

In [21]:
valor_maximo = array.max()
valor_maximo

99

In [22]:
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

3

In [23]:
valor_minimo = array.min()
valor_minimo

1

In [24]:
posicion_valor_minimo = array.argmin()
posicion_valor_minimo

37

---
### Numpy - Indexación en arrays

In [26]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array[0]

0

In [28]:
array[-1]

9

In [29]:
array[2:4]

array([2, 3])

In [30]:
array[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
array[:8:2]

array([0, 2, 4, 6])

In [32]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array2[0] = 100
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---
### Numpy - Indexación en arrays de 2 o más dimensiones

In [36]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
array[0]

array([1, 2, 3])

In [38]:
array2 = array[:2]
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
array[0][0]

1

In [40]:
array[1,1]

5

In [41]:
array[:,0] # selecciona la columna 0 de la matriz

array([1, 4, 7])

In [42]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

---
### Numpy - Seleccionar elementos de un array según una condición

In [44]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
condicion = array > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [46]:
array[condicion]

array([6, 7, 8, 9])

In [47]:
array[array < 2]

array([0, 1])

In [48]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

---
### Numpy - Operaciones sobre los arrays

In [100]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [104]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [112]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [116]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [120]:
np.sqrt(array2) # raiz cuadrada

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])