**Ejercicio 1**
  
- Crear una lista "asisgnaturas" con los textos "matemáticas", "fisica" , "historia"
- Crear una lista  "notas" con los valores 9,9,8
- Crear una serie con la lista "notas" como valores y la lista "asignaturas" como índices
- Crear la variable "nota_fisica" con la nota de la asignatura física
- Mediante el método print muestra la frase "La nota de física es un ..." 

In [19]:
import pandas as pd

In [88]:
asignaturas = 'matemáticas fisica historia'.split()
asignaturas

['matemáticas', 'fisica', 'historia']

In [92]:
notas = [9,9,8]
notas

[9, 9, 8]

In [94]:
serie = pd.Series(data=notas, index=asignaturas)
serie

matemáticas    9
fisica         9
historia       8
dtype: int64

In [96]:
nota_fisica = serie['fisica']

In [98]:
print('La nota de física es un {}'.format(nota_fisica))

La nota de física es un 9


---
**Ejercicio 2**

El objetivo será crear un dataframe con las ventas de nuestras 3 oficinas para los meses de enero, febrero y marzo.
- Crear una variable "ventas_enero" que contenga una lista de 3 números enteros aleatorios entre 100 y 500.
- Crear una variable "ventas_febrero" que contenga una lista de 3 números enteros aleatorios entre 100 y 500.
- Crear una variable "ventas_marzo" que contenga una lista de 3 números enteros aleatorios entre 100 y 500.
- Crear una variable "filas" que contenga esta lista de palabras: "ventas_enero", "ventas_febrero", "ventas_marzo".
- Crear una variable "columnas" que contenga esta lista de palabras: "oficina_1", "oficina_2", "oficina_3".
- Crear una variable "ventas" que contenta una lista con los valores de ventas de enero, febrero y marzo.
- Crear un dataframe "datafame" que contenga las ventas, filas y columnas.
- Mediante print muestra el valor de "Las ventas de enero para la oficina 1 son de ..."

In [161]:
import numpy as np
import pandas as pd

In [163]:
ventas_enero = np.random.randint(100, 500, 3)
ventas_enero

array([239, 156, 498])

In [165]:
ventas_febrero = np.random.randint(100, 500, 3)
ventas_febrero

array([405, 148, 493])

In [167]:
ventas_marzo = np.random.randint(100, 500, 3)
ventas_marzo

array([323, 209, 319])

In [169]:
filas = 'ventas_enero ventas_febrero ventas_marzo'.split()
filas

['ventas_enero', 'ventas_febrero', 'ventas_marzo']

In [171]:
columnas = 'oficina_1 oficina_2 oficina3_'.split()
columnas

['oficina_1', 'oficina_2', 'oficina3_']

In [173]:
ventas = [ventas_enero, ventas_febrero, ventas_marzo]
ventas

[array([239, 156, 498]), array([405, 148, 493]), array([323, 209, 319])]

In [175]:
dataframe = pd.DataFrame(data=ventas, index=filas, columns=columnas)
dataframe

oficina_1  oficina_2  oficina3_
ventas_enero          239        156        498
ventas_febrero        405        148        493
ventas_marzo          323        209        319

In [181]:
print('Las ventas de enero para la oficina 1 son de {}'.format(dataframe['oficina_1']['ventas_enero']))

Las ventas de enero para la oficina 1 son de 239
